import SessionProvider from '@libs/nextauth';
import { ThemeProvider } from '@theme';
import type { Metadata, Viewport } from 'next';
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

const MINUTES = 60;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <SessionProvider refetchInterval={7 * MINUTES}>
          <ThemeProvider>{children}</ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
